Repository Automattic/msm-sitemap, pull requests merged in 2025-07, with the labels that each got.

#190 test: Add testdox argument
  phpunit.xml.dist
Labels: Type: maintenance

#191 Refactor FunctionsTest for clarity and consistency
  tests/FunctionsTest.php
Labels: Type: maintenance, Component: Tests

#192 test: Increase WP max version for tests
  .github/workflows/integrations.yml
Labels: Type: maintenance, Components: CI

#193 test: Refactor test methods into TestCase
  phpunit.xml.dist
  tests/CPTTest.php
  tests/CreationTest.php
  tests/CronTest.php
  tests/FunctionsTest.php
  tests/IndexesTest.php
  tests/SitemapCliTest.php
  tests/StatsTest.php
  tests/TestCase.php
Labels: Type: maintenance, Component: Tests

#195 Allow the post year range to be short-circuited and also cached
  msm-sitemap.php
  tests/FiltersTest.php
  tests/FunctionsTest.php
Labels: Type: enhancement

#122 If all posts were skipped, remove the sitemap post.
  msm-sitemap.php
  tests/CreationTest.php
Labels: Type: bug

#197 feat: Add filters for sitemap index XML customization
  msm-sitemap.php
  tests/FiltersTest.php
Labels: Type: enhancement

#198 Add lots of tests
  languages/msm-sitemap.pot
  msm-sitemap.php
  tests/AdminPageTest.php
  tests/AjaxEndpointTest.php
  tests/CreationTest.php
  tests/DateRangeHasPostsTest.php
  tests/FunctionsTest.php
  tests/GenerateSitemapTest.php
  tests/GetPostIdsForDateTest.php
  tests/Includes/CustomPostStatusTestTrait.php
  tests/Includes/mock-wp-cli.php
  tests/RobotsTest.php
  tests/SitemapCliTest.php
  tests/SitemapIndexXmlTest.php
Labels: Type: maintenance

#200 docs: Add developer documentation and updated README
  DEVELOPERS.md
  README.md
Labels: Type: documentation

#201 Add custom post permalink handling for msm_sitemap posts
  includes/Permalinks.php
  msm-sitemap.php
  tests/PermalinksTest.php
Labels: Type: bug

#202 feat: Enhance WP-CLI commands for Metro Sitemap
  DEVELOPERS.md
  README.md
  includes/wp-cli.php
  msm-sitemap.php
  tests/Cli/DeleteTest.php
  tests/Cli/ExportTest.php
  tests/Cli/GetTest.php
  tests/Cli/ListTest.php
  tests/Cli/RecountTest.php
  tests/Cli/StatsTest.php
  tests/Cli/ValidateTest.php
  tests/Includes/mock-wp-cli.php
  tests/SitemapCliTest.php
Labels: Type: enhancement, Components: CLI

#204 Release 1.5.0 into develop
  CHANGELOG.md
  README.md
  includes/wp-cli.php
  languages/msm-sitemap.pot
  msm-sitemap.php
  tests/Cli/ValidateTest.php
Labels: Type: maintenance

#206 feat: Add XSL stylesheets to XML sitemaps
  includes/CoreIntegration.php
  includes/StylesheetManager.php
  msm-sitemap.php
  tests/CoreIntegrationTest.php
  tests/StylesheetManagerTest.php
Labels: Type: enhancement

#207 feat: Add sitemap_url to list and get CLI output
  includes/wp-cli.php
  tests/Cli/GetTest.php
  tests/Cli/ListTest.php
Labels: Type: enhancement

#169 Add a post_status/post_type to query for performance
  msm-sitemap.php
Labels: Type: enhancement, Status: needs review

#211 fix: Add post deletion handling to update sitemap
  msm-sitemap.php
  tests/CronTest.php
  tests/PostDeletionTest.php
Labels: Type: bug

#212 style: fix more code style violations
  includes/CoreIntegration.php
  tests/Cli/ExportTest.php
  tests/Cli/ListTest.php
  tests/CoreIntegrationTest.php
  tests/DateRangeHasPostsTest.php
  tests/FunctionsTest.php
  tests/GetPostIdsForDateTest.php
  tests/Includes/mock-wp-cli.php
  tests/RobotsTest.php
  tests/StylesheetManagerTest.php
  tests/TestCase.php
  tests/bootstrap.php
Labels: Type: maintenance
